export const ENV = {
  appId: process.env.VITE_APP_ID ?? "",
  cookieSecret: process.env.JWT_SECRET ?? "",
  databaseUrl: process.env.DATABASE_URL ?? "",
  oAuthServerUrl: process.env.OAUTH_SERVER_URL ?? "",
  ownerOpenId: process.env.OWNER_OPEN_ID ?? "",
  isProduction: process.env.NODE_ENV === "production",
  forgeApiUrl: process.env.BUILT_IN_FORGE_API_URL ?? "",
  forgeApiKey: process.env.BUILT_IN_FORGE_API_KEY ?? "",
  graph: {
    sourceTenantId: process.env.MS_GRAPH_SOURCE_TENANT_ID ?? "",
    sourceClientId: process.env.MS_GRAPH_SOURCE_CLIENT_ID ?? "",
    sourceClientSecret: process.env.MS_GRAPH_SOURCE_CLIENT_SECRET ?? "",
    targetTenantId: process.env.MS_GRAPH_TARGET_TENANT_ID ?? "",
    targetClientId: process.env.MS_GRAPH_TARGET_CLIENT_ID ?? "",
    targetClientSecret: process.env.MS_GRAPH_TARGET_CLIENT_SECRET ?? "",
  },
  sharePoint: {
    targetSiteUrl: process.env.MS_SHAREPOINT_TARGET_SITE_URL ?? "",
    targetWebId: process.env.MS_SHAREPOINT_TARGET_WEB_ID ?? "",
    sourceContainerSasUri: process.env.MS_SHAREPOINT_SOURCE_CONTAINER_SAS_URI ?? "",
    manifestContainerSasUri: process.env.MS_SHAREPOINT_MANIFEST_CONTAINER_SAS_URI ?? "",
    queueReportSasUri: process.env.MS_SHAREPOINT_QUEUE_REPORT_SAS_URI ?? "",
  },
};
